spring:
  datasource:
    url: ${BOYCOTT_DB}
    username: ${BOYCOTT_DB_USER}
    password: ${BOYCOTT_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect